name: travelplanner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  blur: ^2.0.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.1.0
  cloud_functions: ^1.0.7
  cupertino_icons: ^1.0.2
  dfunc: ^0.6.2
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  firebase_messaging: ^9.1.4
  firebase_storage: ^8.0.6
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  formz: ^0.4.0
  freezed_annotation: ^0.14.1
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.4
  google_sign_in: ^5.0.3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  meta: ^1.3.0
  shared_preferences: ^2.0.5
  tuple: ^2.0.0
  velocity_x: ^3.0.0
  weather: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_gen_runner: ^3.1.1
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  lint: ^1.5.3

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
  # colors:
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  assets:
    - assets/icons/custom/
    - assets/icons/unicons_line/
    - assets/icons/unicons_monochrome/
    - assets/icons/unicons_solid/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-RegularItalic.otf
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
          style: italic
          weight: 700
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/proxima_nova/ProximaNova-Regular.otf
        - asset: assets/fonts/proxima_nova/Proxima Nova Alt Regular.otf
        - asset: assets/fonts/proxima_nova/Proxima Nova Alt Regular Italic.otf
          style: italic
          weight: 700
